// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFj_1TGVFZFHHoJ3jTsoP1HP3iXoVLKKs',
    appId: '1:616122820038:web:c648527b9f22244c0b7ec7',
    messagingSenderId: '616122820038',
    projectId: 'chatappflutter-f1370',
    authDomain: 'chatappflutter-f1370.firebaseapp.com',
    storageBucket: 'chatappflutter-f1370.appspot.com',
    measurementId: 'G-92EW567LJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6icrCE-FNTCZ_Uz0Dn5H-MQsyASDX75o',
    appId: '1:616122820038:android:0cff07b8fd1dac240b7ec7',
    messagingSenderId: '616122820038',
    projectId: 'chatappflutter-f1370',
    storageBucket: 'chatappflutter-f1370.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1u-oCxCsxug3VGizyOsE3pL_se6Hx9A',
    appId: '1:616122820038:ios:5f1671d54fa8b1140b7ec7',
    messagingSenderId: '616122820038',
    projectId: 'chatappflutter-f1370',
    storageBucket: 'chatappflutter-f1370.appspot.com',
    iosClientId: '616122820038-e73qi860jvo0r0i01k29vpeipvlbso27.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1u-oCxCsxug3VGizyOsE3pL_se6Hx9A',
    appId: '1:616122820038:ios:5f1671d54fa8b1140b7ec7',
    messagingSenderId: '616122820038',
    projectId: 'chatappflutter-f1370',
    storageBucket: 'chatappflutter-f1370.appspot.com',
    iosClientId: '616122820038-e73qi860jvo0r0i01k29vpeipvlbso27.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappflutter',
  );
}
